---
:project:
  :use_exceptions: TRUE
  :use_mocks: TRUE
  :use_test_preprocessor: TRUE
  :use_preprocessor_directives: FALSE
  :use_auxiliary_dependencies: TRUE
  :auto_link_deep_dependencies: TRUE
  :build_root: build
  :release_build: FALSE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.30.0
  :default_tasks:
    - test:all

:paths:
  :test:
    - +:test/**
    - +:test/support
    - +:test/support/stubs
  :source:
    - src/**
  :include:
    - src/
  :support:
    - test/support
    - test/support/stubs/**
  :libraries: []

:defines:
  :test:
    - TEST
    - CRC8_TABLE
    - CRC16_TABLE
    - CRC32_TABLE

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
    - :expect_any_args
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:gcov:
  :utilities:
    - gcovr           # Use gcovr to create the specified reports (default).
  :reports:
    - HtmlDetailed
    - JSON
    - Cobertura
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90
    :branches: true
    :print_summary: true

# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []
  :test: []
  :release: []

:tools:
  :gcov_compiler:
    :executable: gcc
    :arguments:
      - -g
      - -fprofile-arcs
      - -ftest-coverage
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -DGCOV_COMPILER
      - -DCODE_COVERAGE
      - -c "${1}"
      - -o "${2}"
  :gcov_linker:
    :executable: gcc
    :arguments:
      - -fprofile-arcs
      - -ftest-coverage
      - ${1}
      - -o ${2}
      - ${4}
      - ${5}
  :gcov_fixture:
    :executable: ${1}
  :gcov_report:
    :executable: gcov
    :arguments:
      - -n
      - -p
      - -b
      - -o "$": GCOV_BUILD_OUTPUT_PATH
      - "\"${1}\""
  :gcov_gcov_post_report:
    :executable: gcov
    :optional: TRUE
    :arguments:
      - ${1}
  :gcov_gcovr_post_report:
    :executable: gcovr
    :optional: TRUE
    :arguments:
      - ${1}
  :gcov_report_generator_post_report:
    :executable: reportgenerator
    :optional: TRUE
    :arguments:
      - ${1}

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_pretty_tests_report
    # - stdout_gtestlike_tests_report
    - module_generator
    - raw_output_report
    - xml_tests_report
    - command_hooks
    - colour_report
    - gcov
