name: UglyContainerBuild

on:
  push:
    branches: 
      - develop
      - master
jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Ceedling Check1
    #   run: ceedling help
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        
    - name: Install dependencies
      run: |
        gem install ceedling

    - name: Ceedling Check2
      run: ceedling help

