name: Doxygen

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install doxygen
      run: |
        sudo apt-get update -qq
        sudo apt-get install doxygen
        
    - name: Run Doxygen
      run: doxygen Doxygen.conf
